### PR TITLE
export ScrollSceneChildProps type

### PR DESCRIPTION
**Pull request by zshannon**
Hey there, thanks for sharing this library. It'd be helpful for me as a typescript user to have a direct handle on this type 🙏

### CODE REVIEW

**Comment by ffdead** [comment]
Thanks @zshannon yes that makes perfect sense - the TS support has been a work in progress so I appreciate the help. Let me know if you notice something else is missing!

**Comment by zshannon** [comment]
That's it for now but will send PRs down the line if something else comes up. Are you up for doing a package release with this typing in it?

**Comment by ffdead** [comment]
Yes, new patch release coming today!

**Comment by ffdead** [comment]
[v8.11.12](https://github.com/14islands/r3f-scroll-rig/commit/3d64d105d04c8f47be0d1be038dd787d44dc027f)

**Pull request merged**
